import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import http from 'node:http';
import { iniciarDistribuidor } from '../lib/distribuidor.mjs';
const esperar = async fn => { for (let i = 0; i < 100; i++) { if (await fn()) return; await new Promise(r => setTimeout(r, 20)); } assert.fail('Tempo esgotado'); };
test('distribuição configurada, watch, escrita parcial, isolamento, falhas e reinício', async t => {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'balde-dist-'));
  t.after(() => fs.rm(dir, { recursive: true, force: true }));
  const destinosPath = path.join(dir, 'DESTINOS.md');
  const fila = path.join(dir, 'fila-distribuicao.jsonl');
  const resultados = async () => { try { return (await fs.readFile(path.join(dir, 'distribuicao-resultados.jsonl'), 'utf8')).trim().split('\n').map(JSON.parse); } catch { return []; } };
  let dist;
  t.after(async () => { await dist?.parar(); });
  const recebidos = [];
  const server = http.createServer((req, res) => { let body = ''; req.on('data', c => body += c); req.on('end', () => { recebidos.push(JSON.parse(body)); res.writeHead(req.url === '/erro' ? 500 : 200); res.end(); }); });
  await new Promise(r => server.listen(0, '127.0.0.1', r));
  t.after(() => new Promise(r => server.close(r)));
  const url = `http://127.0.0.1:${server.address().port}`;
  const comando = path.join(dir, 'executar com espaços');
  await fs.writeFile(comando, `#!${process.execPath}\nrequire('node:fs').writeFileSync(${JSON.stringify(path.join(dir, 'saida'))}, JSON.stringify(process.argv.slice(2)));`);
  await fs.chmod(comando, 0o755);
  await fs.writeFile(destinosPath, `| Nome | Tipo | Alvo |\n|---|---|---|\n| Local | agente | operador |\n| HTTP | webhook | ${url} |\n| Erro | webhook | ${url}/erro |\n| Script | comando | ${comando} |\n`);
  await fs.writeFile(path.join(dir, 'tarefas.json'), JSON.stringify([{ id: 't1', chatId: 'c1', titulo: 'Café', descricao: 'Preparar entrega', fontes: ['m1'], criterioPronto: 'Arquivo validado' }]));
  await fs.writeFile(path.join(dir, 'mensagens.jsonl'), [{ id: 'm1', chatId: 'c1', texto: 'Fonte á', transcricao: 'Áudio' }, { id: 'm2', chatId: 'c1', texto: 'Não incluir' }].map(JSON.stringify).join('\n') + '\n');
  await fs.mkdir(path.join(dir, 'contextos'));
  await fs.writeFile(path.join(dir, 'contextos/c1.json'), '{"resumo":"Contexto independente"}');
  const entrada = destino => JSON.stringify({ tarefaId: 't1', destino }) + '\n';
  await fs.writeFile(fila, entrada('HTTP'));
  dist = await iniciarDistribuidor({ dadosDir: dir, destinosPath });
  assert.equal(recebidos.length, 1);
  assert.equal(recebidos[0].mensagens_fonte.length, 1);
  await fs.appendFile(fila, entrada('Local').slice(0, -1));
  await new Promise(r => setTimeout(r, 60));
  assert.equal((await resultados()).length, 1);
  await fs.appendFile(fila, '\n');
  await esperar(async () => (await resultados()).length === 2);
  const briefing = await fs.readFile(path.join(dir, 'despacho/t1.md'), 'utf8');
  for (const texto of ['Contexto independente', 'Preparar entrega', 'Arquivo validado', 'Fonte á', 'Áudio']) assert.ok(briefing.includes(texto));
  assert.ok(!briefing.includes('Não incluir'));
  await fs.appendFile(fila, entrada({ tipo: 'comando', alvo: comando }) + entrada('Erro') + entrada({ tipo: 'webhook', alvo: 'https://nao-autorizado.invalid' }) + '{invalido}\n');
  await esperar(async () => (await resultados()).length === 6);
  assert.deepEqual(JSON.parse(await fs.readFile(path.join(dir, 'saida'), 'utf8')), [path.join(dir, 'despacho/t1.md')]);
  assert.deepEqual((await resultados()).map(r => r.ok), [true, true, true, false, false, false]);
  await dist.parar();
  // Simula resultado persistido antes do offset: não repete o POST.
  await fs.writeFile(path.join(dir, 'distribuidor.offset'), '0');
  dist = await iniciarDistribuidor({ dadosDir: dir, destinosPath });
  assert.equal((await resultados()).length, 6);
  assert.equal(recebidos.length, 2);
  await fs.appendFile(fila, entrada('Local'));
  await esperar(async () => (await resultados()).length === 7);
  await dist.parar();
  const anterior = process.env.BALDE_DADOS;
  process.env.BALDE_DADOS = dir;
  try { dist = await iniciarDistribuidor({ destinosPath }); assert.equal((await resultados()).length, 7); }
  finally { if (anterior === undefined) delete process.env.BALDE_DADOS; else process.env.BALDE_DADOS = anterior; }
});
